package com.intellibucket.pipeql.view.util;

import java.awt.*;

public class FontsUtil {
    public static final Font ARIAL_PLAIN_12 = new Font("Arial", Font.PLAIN, 12);
    public static final Font ARIAL_PLAIN_14 = new Font("Arial", Font.PLAIN, 14);
    public static final Font ARIAL_PLAIN_16 = new Font("Arial", Font.PLAIN, 16);
    public static final Font ARIAL_PLAIN_18 = new Font("Arial", Font.PLAIN, 18);
    public static final Font ARIAL_PLAIN_20 = new Font("Arial", Font.PLAIN, 20);
    public static final Font ARIAL_PLAIN_22 = new Font("Arial", Font.PLAIN, 22);
    public static final Font ARIAL_PLAIN_24 = new Font("Arial", Font.PLAIN, 24);
    public static final Font ARIAL_PLAIN_26 = new Font("Arial", Font.PLAIN, 26);
    public static final Font ARIAL_PLAIN_28 = new Font("Arial", Font.PLAIN, 28);
    public static final Font ARIAL_PLAIN_30 = new Font("Arial", Font.PLAIN, 30);
    public static final Font ARIAL_PLAIN_32 = new Font("Arial", Font.PLAIN, 32);
    public static final Font ARIAL_PLAIN_34 = new Font("Arial", Font.PLAIN, 34);
    public static final Font HELVETICA_PLAIN_12 = new Font("Helvetica", Font.PLAIN, 12);
    public static final Font HELVETICA_PLAIN_14 = new Font("Helvetica", Font.PLAIN, 14);
    public static final Font HELVETICA_PLAIN_16 = new Font("Helvetica", Font.PLAIN, 16);
    public static final Font HELVETICA_PLAIN_18 = new Font("Helvetica", Font.PLAIN, 18);
    public static final Font HELVETICA_PLAIN_20 = new Font("Helvetica", Font.PLAIN, 20);
    public static final Font HELVETICA_PLAIN_22 = new Font("Helvetica", Font.PLAIN, 22);
    public static final Font HELVETICA_PLAIN_24 = new Font("Helvetica", Font.PLAIN, 24);
    public static final Font HELVETICA_PLAIN_26 = new Font("Helvetica", Font.PLAIN, 26);
    public static final Font HELVETICA_PLAIN_28 = new Font("Helvetica", Font.PLAIN, 28);
    public static final Font HELVETICA_PLAIN_30 = new Font("Helvetica", Font.PLAIN, 30);
    public static final Font HELVETICA_PLAIN_32 = new Font("Helvetica", Font.PLAIN, 32);
    public static final Font HELVETICA_PLAIN_34 = new Font("Helvetica", Font.PLAIN, 34);
    public static final Font HELVETICA_PLAIN_36 = new Font("Helvetica", Font.PLAIN, 36);
    public static final Font HELVETICA_PLAIN_38 = new Font("Helvetica", Font.PLAIN, 38);
    public static final Font ROBOTO_PLAIN_12 = new Font("Roboto", Font.PLAIN, 12);
    public static final Font ROBOTO_PLAIN_14 = new Font("Roboto", Font.PLAIN, 14);
    public static final Font ROBOTO_PLAIN_16 = new Font("Roboto", Font.PLAIN, 16);
    public static final Font ROBOTO_PLAIN_18 = new Font("Roboto", Font.PLAIN, 18);
    public static final Font ROBOTO_PLAIN_20 = new Font("Roboto", Font.PLAIN, 20);
    public static final Font ROBOTO_PLAIN_22 = new Font("Roboto", Font.PLAIN, 22);
    public static final Font ROBOTO_PLAIN_24 = new Font("Roboto", Font.PLAIN, 24);
    public static final Font ROBOTO_PLAIN_26 = new Font("Roboto", Font.PLAIN, 26);
    public static final Font ROBOTO_PLAIN_28 = new Font("Roboto", Font.PLAIN, 28);
    public static final Font ROBOTO_PLAIN_30 = new Font("Roboto", Font.PLAIN, 30);
    public static final Font ROBOTO_PLAIN_32 = new Font("Roboto", Font.PLAIN, 32);
    public static final Font ROBOTO_PLAIN_34 = new Font("Roboto", Font.PLAIN, 34);
    public static final Font ROBOTO_PLAIN_36 = new Font("Roboto", Font.PLAIN, 36);
    public static final Font ROBOTO_PLAIN_38 = new Font("Roboto", Font.PLAIN, 38);
    public static final Font ROBOTO_PLAIN_40 = new Font("Roboto", Font.PLAIN, 40);
    public static final Font RAJDHANI_PLAIN_12 = new Font("Rajdhani", Font.PLAIN, 12);
    public static final Font RAJDHANI_PLAIN_14 = new Font("Rajdhani", Font.PLAIN, 14);
    public static final Font RAJDHANI_PLAIN_16 = new Font("Rajdhani", Font.PLAIN, 16);
    public static final Font RAJDHANI_PLAIN_18 = new Font("Rajdhani", Font.PLAIN, 18);
    public static final Font RAJDHANI_PLAIN_20 = new Font("Rajdhani", Font.PLAIN, 20);
    public static final Font RAJDHANI_PLAIN_22 = new Font("Rajdhani", Font.PLAIN, 22);
    public static final Font RAJDHANI_PLAIN_24 = new Font("Rajdhani", Font.PLAIN, 24);
    public static final Font RAJDHANI_PLAIN_26 = new Font("Rajdhani", Font.PLAIN, 26);
    public static final Font RAJDHANI_PLAIN_28 = new Font("Rajdhani", Font.PLAIN, 28);
    public static final Font RAJDHANI_PLAIN_30 = new Font("Rajdhani", Font.PLAIN, 30);
    public static final Font RAJDHANI_PLAIN_32 = new Font("Rajdhani", Font.PLAIN, 32);
    public static final Font RAJDHANI_PLAIN_34 = new Font("Rajdhani", Font.PLAIN, 34);
    public static final Font RAJDHANI_PLAIN_36 = new Font("Rajdhani", Font.PLAIN, 36);
    public static final Font RALEWAY_PLAIN_12 = new Font("Raleway", Font.PLAIN, 12);
    public static final Font RALEWAY_PLAIN_14 = new Font("Raleway", Font.PLAIN, 14);
    public static final Font RALEWAY_PLAIN_16 = new Font("Raleway", Font.PLAIN, 16);
    public static final Font RALEWAY_PLAIN_18 = new Font("Raleway", Font.PLAIN, 18);
    public static final Font RALEWAY_PLAIN_20 = new Font("Raleway", Font.PLAIN, 20);
    public static final Font RALEWAY_PLAIN_22 = new Font("Raleway", Font.PLAIN, 22);
    public static final Font RALEWAY_PLAIN_24 = new Font("Raleway", Font.PLAIN, 24);
    public static final Font RALEWAY_PLAIN_26 = new Font("Raleway", Font.PLAIN, 26);
    public static final Font RALEWAY_PLAIN_28 = new Font("Raleway", Font.PLAIN, 28);
    public static final Font RALEWAY_PLAIN_30 = new Font("Raleway", Font.PLAIN, 30);
    public static final Font RALEWAY_PLAIN_32 = new Font("Raleway", Font.PLAIN, 32);
    public static final Font RALEWAY_PLAIN_34 = new Font("Raleway", Font.PLAIN, 34);
    public static final Font RALEWAY_PLAIN_36 = new Font("Raleway", Font.PLAIN, 36);


    public static final Font HELVETICA_BOLD_14 = new Font("Helvetica", Font.BOLD, 14);
    public static final Font HELVETICA_BOLD_16 = new Font("Helvetica", Font.BOLD, 16);
}
