package com.intellibucket.pipeql.domain.model.json.type.db;

public enum OracleDataType {
    VARCHAR,
    VARCHAR2,
    NUMBER,
    DATE,
    TIMESTAMP,
    CLOB,
    BLOB,
    BFILE,
    RAW,
    LONG,
    LONG_RAW,
    ROWID,
    UROWID,
    CHAR,
    NCHAR,
    NVARCHAR2,
    NCLOB,
    BINARY_FLOAT,
    BINARY_DOUBLE,
    XMLTYPE,
    INTERVAL_YEAR_TO_MONTH,
    INTERVAL_DAY_TO_SECOND,
    TIMESTAMP_WITH_TIME_ZONE,
    TIMESTAMP_WITH_LOCAL_TIME_ZONE,
    OBJECT,
    VARRAY,
    TABLE,
    REF,
    ANYTYPE,
    ANYDATA,
    ANYDATASET,
    ANYSCHEMA,
    ANYPLSQL,
    ANYDATA_CONSTRUCTOR,
    SYS_REFCURSOR,
    REFGROUP;

}
